# Generated by Django 3.2.13 on 2022-04-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rename_guest_room_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bath',
        ),
    ]
