# Generated by Django 3.2.13 on 2022-04-20 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220420_1913'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20220420_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListModel',
            new_name='List',
        ),
    ]
