# Generated by Django 3.2.13 on 2022-04-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_listmodel_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='room',
            new_name='rooms',
        ),
    ]
